[package]
name = "metaschema-gen"
version = "0.1.0"
edition = "2021"
rust-version = "1.56.0"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
anyhow = "1"
unc-abi = { path = "../unc-abi" }
schemars = { version = "0.8.11", features = ["impl_json_schema"] }
serde_json = "1"
